"""Type-safe Pydantic Response Schemas for Vertex AI Gemini Structured Output and ADK Tools."""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Literal, Type
from pydantic import BaseModel, Field


class IdeaProposal(BaseModel):
    """Schema for an individual prototype proposal synthesized by the Planner Agent."""
    id: str = Field(description="Unique identifier for the proposal (e.g. idea_a_event_fleet)")
    title: str = Field(description="Catchy enterprise prototype name")
    summary: str = Field(description="2-3 sentence executive synopsis of the prototype")
    tech_stack: List[str] = Field(description="Google Cloud & cross-platform technologies used (e.g., Flutter, Dart, Firebase, Vertex AI)")
    track_fit: str = Field(description="Target competition track or enterprise theme")
    impact: str = Field(description="Target business or architectural impact metrics")
    repo_name: str = Field(
        description="Sanitized slug for the Git repository (e.g. catchyworks-fleet-prototype)",
        pattern=r"^[a-z0-9\-]+$"
    )


class DualProposalResponse(BaseModel):
    """Schema for the mandatory 2-idea proposal formulation from the Planner Agent."""
    idea_a: IdeaProposal = Field(description="Concept A: High-throughput polyglot execution proposal")
    idea_b: IdeaProposal = Field(description="Concept B: Privacy-preserving compliance & governance proposal")
    reasoning: str = Field(description="Planner reasoning explaining why both ideas match the constraints")


class ArchitectureComponent(BaseModel):
    name: str = Field(description="Service or component name")
    service_type: str = Field(description="e.g. Cloud Run, Cloud SQL, Vertex AI, Pub/Sub, Cloud Storage, Firebase Hosting")
    role: str = Field(description="Specific role of this component")


class ArchitectureSpec(BaseModel):
    """Schema for the system architecture designed by the Architect Agent."""
    title: str = Field(description="Architecture title")
    compute_target: str = Field(default="Google Cloud Run (min-instances=0)")
    session_store: str = Field(default="Cloud SQL PostgreSQL (with RLS)")
    vector_memory_store: str = Field(default="Cloud SQL pgvector (text-embedding-005)")
    git_provider: Literal["github", "gitlab"] = Field(default="github", description="Target Git hosting provider")
    components: List[ArchitectureComponent] = Field(default_factory=list)
    diagram_mermaid: str = Field(
        description="Valid Mermaid syntax markdown diagram representing the topology. EXACT RULE: Return RAW text only. DO NOT wrap in markdown ```mermaid``` code blocks."
    )


class FileRequest(BaseModel):
    """Spec for a file in the scaffolding plan."""
    path: str = Field(description="Relative path of the file (e.g. src/main.py or lib/main.dart)")
    purpose: str = Field(description="Description of what this file contains")
    is_critical_for_review: bool = Field(default=False, description="Whether this file requires CEO review before commit")


class GeneratedFile(BaseModel):
    """Schema for code generated by the Lead Dev Agent."""
    path: str = Field(description="Relative file path")
    content: str = Field(
        description="Complete source code content for this file. EXACT RULE: Return RAW text only. DO NOT wrap in markdown ``` code blocks."
    )
    language: str = Field(default="python", description="Programming or config language (e.g., python, dart, yaml, json)")
    commit_message: str = Field(description="Meaningful Git commit message")
    is_critical_for_review: bool = Field(default=False)


class SubmissionPackage(BaseModel):
    """Schema for final hackathon and marketing deliverables synthesized by the Marketing Agent."""
    title: str = Field(description="Project title for submission")
    tagline: str = Field(description="1-line impactful elevator pitch", max_length=100)
    demo_script_markdown: str = Field(description="4-minute minute-by-minute demo video script")
    devpost_description: str = Field(description="Full formatted markdown text description for Devpost")
    features_and_functionality: List[str] = Field(description="Bullet points of key features")
    technologies_used: List[str] = Field(description="List of Google Cloud and third-party technologies")
    learnings: str = Field(description="Key findings, engineering takeaways, and scalability observations")


class CodeReviewFinding(BaseModel):
    """A single concrete issue found during code review."""
    severity: Literal["critical", "warning", "info"] = Field(
        description="critical = must fix before merge, warning = should fix, info = suggestion"
    )
    file: str = Field(description="Relative file path the finding applies to (or 'general')")
    issue: str = Field(description="Clear, concise description of the problem")
    suggestion: str = Field(description="Actionable fix the Lead Dev should apply")


class CodeReview(BaseModel):
    """Schema for the Reviewer Agent verdict on generated code.

    The reviewer is an INDEPENDENT critic: it checks the implementation
    against (1) the Architect's topology, (2) the hackathon rules/requirements,
    and (3) basic correctness/quality. It never lobbies for its own creation —
    it collaborates with the Lead Dev by sending findings back for rework.
    """
    verdict: Literal["approve", "needs_work"] = Field(
        description="approve only when all critical and warning findings are resolved"
    )
    summary: str = Field(description="1-3 sentence overall assessment")
    findings: List[CodeReviewFinding] = Field(default_factory=list)
    rework_feedback: str = Field(
        description="Direct, actionable instruction block for the Lead Dev Agent "
                    "— what to change and where. Empty when verdict is 'approve'."
    )


# =====================================================================
# ADK ALIASES & SCHEMA REGISTRY (ADK Integration Optimization)
# =====================================================================

AdkIdeaProposal = IdeaProposal
AdkDualProposalResponse = DualProposalResponse
AdkArchitectureComponent = ArchitectureComponent
AdkArchitectureSpec = ArchitectureSpec
AdkFileRequest = FileRequest
AdkGeneratedFile = GeneratedFile
AdkSubmissionPackage = SubmissionPackage
AdkCodeReview = CodeReview
AdkCodeReviewFinding = CodeReviewFinding


class AdkSchemaRegistry:
    """Helper registry to generate OpenAI / ADK compatible JSON schemas for Vertex AI structured outputs."""
    
    @classmethod
    def get_json_schema(cls, model_class: Type[BaseModel]) -> Dict[str, Any]:
        """Converts Pydantic models into OpenAPI/ADK compatible JSON schema dictionaries."""
        return model_class.model_json_schema()